# Análisis e Implementación en SparkQL

* Entrega hasta el 24 de mayo en https://forms.gle/aRiWtjayausRFCTd8

* Los dos conjuntos de datos entregados, CSV separados por coma, Evaluación del Pitch (2021.04.13 ISoftware).csv y Asistencia del Pitch (2021.04.13 ISoftware).csv proceden de dos encuestas realizadas con Google Forms.

* Los archivos proceden de las evaluaciones de los pitch (exposiciones cortas de negocio) que realizan los estudiantes de la asignatura de Ingeniería de Software. Los estudiantes están organizados en equipos. Cada equipo realiza una presentación de máximo 15 minutos, una vez inicia la presentación todos los estudiantes deben registrar su asistencia lo cual queda registrado en 'Asistencia del Pitch (2021.04.13 ISoftware).csv' incluidos los miembros del equipo.

* El archivo `Asistencia del Pitch (2021.04.13 ISoftware).csv` contiene las columnas: `"Marca temporal"` es tiempo dado en fecha y hora, `"Nombre de usuario"` es el correo electrónico del estudiante y es texto,`"Equipo al que perteneces:"` equipo de trabajo al que pertenece el estudiante también es texto y `"Equipo que va a exponer:"` equipo que el estudiante va a tender a su presentación.

* El archivo `Evaluación del Pitch (2021.04.13 ISoftware).csv` contiene las columnas `"Marca temporal"` es tiempo dado en fecha y hora, `"Nombre de usuario"` es el correo electrónico del estudiante y es texto, `"Equipo que vas a evaluar:"` equipo que ha expuesto y que va a ser evaluado por cada estudiante que no sea integrante; a continuación, se tienen las siguientes columnas que corresponden a la evaluación de los respectivos ítems:

    1. "Introducción: El equipo responde adecuadamente ¿Quiénes son y por qué están aquí?",
    2. "Equipo: El equipo responde adecuadamente ¿Quiénes están detrás de la idea y cuál es su función?",
    3. "Problema: El equipo responde adecuadamente ¿Qué problema resolverá?, ¿es realmente un problema?",
    4. "Ventajas: El equipo responde adecuadamente ¿Por qué su solución es especial?, ¿qué la hace distinta de otras?",
    5. "Solución: El equipo responde adecuadamente ¿Cómo piensa resolver el problema?",
    6. "Producto: El equipo responde adecuadamente ¿Cómo funciona el producto o servicio? Muestra algunos ejemplos.",
    7. "Tracción: El equipo responde adecuadamente si cuenta con clientes que demuestran potencial.",
    8. "Mercado: El equipo responde conoce, o por lo menos intentar predecir, el tamaño del mercado que impactará.",
    9. "Competencia: El equipo responde adecuadamente ¿Cuáles son las soluciones alternativas al problema que plantea?",
    10. "Modelo de negocio: El equipo responde adecuadamente ¿Cómo hará dinero? ",
    11. "Inversión: El equipo responde adecuadamente ¿Cuál es su presupuesto y cuánto espera ganar?",
    12. "Contacto: El equipo deja los datos al cliente y muestra cómo pueden contactarle.",
    13. "Exposición: ¿Qué tan coordinados estaban los expositores?",
    14. "Exposición: ¿Los expositores se expresaron con claridad y se hicieron entender?",
    15. "Exposición: Las diapositivas son claras y coherentes y apoyaron adecuadamente la exposición.",
    * "Suponiendo que eres inversionista, ¿Estarías dispuesto a invertir dinero en este equipo? (esta pregunta no se pondera en la nota)",
    * "Observaciones para el equipo, estas observaciones las debe considerar el equipo para mejorar la siguiente presentación."


* Cada ítem se evalúa con la siguiente escala: 0. Ausente; 1. Deficiente; 2. Regular; 3. Aceptable; 4. Bueno; 5. Excelente

* Carge los datos, cada archivo en una tabla SparkSQL y responda cada una de las consultas dadas en cada celda. Tenga en cuenta que algunas consultas pueden tener como resultado el vacío.

# Integrantes del equipo
1. Andres Felipe Ortega Lucero - 1082657705
2. Daniel Arroyave Lopez - 1128448929
3. Evelin Calderón Caro - 1152707862
4. Rafael Eduardo Ropero Layton - 1118566826
5. Viviana Posada Restrepo - 1033339284

In [1]:
# Agrege acá el código para importar las librerias
!pip3 install Cython  ##Librerias desarrolladas en C
!pip3 install pyarrow==0.9.0 ##Procesamiento distribuido de arreglos
!pip3 install ts-flint ##Administracion de series de tiempo
!wget https://repo1.maven.org/maven2/com/twosigma/flint/0.6.0/flint-0.6.0.jar

import os
##pasamos a la variable PYSPARK_SUBMIT_ARGS las librerias de java
os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /datalake/flint-0.6.0.jar --py-files /datalake/flint-0.6.0.jar pyspark-shell'

# La libreria para "encontrar el sevicio" de Spark
import findspark
findspark.init()

# Librerias para "gestionar el servicio" de Spark
from pyspark import SparkConf, SparkContext
from pyspark.sql import SQLContext, SparkSession

# Creamos una aplicación Spark en el Servicio
# Tenga cuidado con las tildes o caracteres especiales en el nombre de la app
AppSpark = SparkConf().setAppName("Evaluacion iSofware")

# definimos un espacio o contexto para la App
ContextoSpark=SparkContext(conf=AppSpark)

# inicio una sesión en el espacio de la App
SesionSpark = SparkSession(ContextoSpark)

# inicio del espacio o contexto SQL
ContextoSql = SQLContext(sparkContext=ContextoSpark, sparkSession=SesionSpark)

Collecting Cython
  Downloading https://files.pythonhosted.org/packages/16/9a/2eece92da53d954cc5ede815f9825b8ec795252471d0772ff9a591166c98/Cython-0.29.23-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
    100% |################################| 2.0MB 145kB/s ta 0:00:01
Installing collected packages: Cython
Successfully installed Cython-0.29.23
Collecting pyarrow==0.9.0
  Downloading https://files.pythonhosted.org/packages/fe/27/576e6c979bfa5f63070f809c930aa85d6198b91d17a64866234597ba861f/pyarrow-0.9.0-cp36-cp36m-manylinux1_x86_64.whl (13.7MB)
    100% |################################| 13.7MB 53kB/s eta 0:00:011  31% |##########                      | 4.4MB 165kB/s eta 0:00:57    56% |##################              | 7.7MB 191kB/s eta 0:00:31
Requirement already satisfied: six>=1.0.0 in /usr/lib/python3/dist-packages (from pyarrow==0.9.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.6/dist-packages (from pyarrow==0.9.0)
Installing collected packages: pyarrow
Successfully installed pyarrow-0.9.0
Collecting ts-flint
  Downloading https://files.pythonhosted.org/packages/bb/f9/afab3946adefd527ca376aa71fdb6cd1ff787940c3f2467de382a8697c9d/ts_flint-0.6.0-py3-none-any.whl
Installing collected packages: ts-flint
Successfully installed ts-flint-0.6.0
--2021-05-22 23:19:57--  https://repo1.maven.org/maven2/com/twosigma/flint/0.6.0/flint-0.6.0.jar
Resolving repo1.maven.org (repo1.maven.org)... 151.101.4.209
Connecting to repo1.maven.org (repo1.maven.org)|151.101.4.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2171677 (2.1M) [application/java-archive]
Saving to: 'flint-0.6.0.jar'

flint-0.6.0.jar     100%[===================>]   2.07M   124KB/s    in 12s

2021-05-22 23:20:09 (182 KB/s) - 'flint-0.6.0.jar' saved [2171677/2171677]

In [2]:
# 1. Cargue los datos en la carpeta datalake y luego del /datalake al HDFS (Hadoop File System)
# Recuerda usar ! para ejecutar el comando en el shell. 
# Tu código a continuación...
!hdfs dfs -copyFromLocal AsistenciaPitch.csv /tmp/
!hdfs dfs -copyFromLocal EvaluacionPitch.csv /tmp/
#!hdfs dfs -rm /tmp/*.csv

In [3]:
# 2. Cree dos tablas SparkSQL y almacene el csv en su correspondiente tabla.
# Observación: tenga especial cuidado con los encabezados de los archivos CSV.
# Usted puede considerar cambiar los encabezados de los CSV originales
# Tu código a continuación...
#sentencia para crear las tablas
#ContextoSql.sql("""DROP TABLE EVALUACION """)
#ContextoSql.sql("""DROP TABLE ASISTENCIA """)

ContextoSql.sql("""
CREATE TABLE IF NOT EXISTS 
EVALUACION (
            MarcaTemporal VARCHAR(100), 
            NombreUsuario VARCHAR(100),
            EquipoEvaluar VARCHAR(100),
            Pregunta1 VARCHAR(10),
            Pregunta2 VARCHAR(10),
            Pregunta3 VARCHAR(10),
            Pregunta4 VARCHAR(10),
            Pregunta5 VARCHAR(10),
            Pregunta6 VARCHAR(10),
            Pregunta7 VARCHAR(10),
            Pregunta8 VARCHAR(10),
            Pregunta9 VARCHAR(10),
            Pregunta10 VARCHAR(10),
            Pregunta11 VARCHAR(10),
            Pregunta12 VARCHAR(10),
            Pregunta13 VARCHAR(10),
            Pregunta14 VARCHAR(10),
            Pregunta15 VARCHAR(10),
            Pregunta16 VARCHAR(10),
            Observaciones VARCHAR(100)
            ) 
USING CSV OPTIONS ( 
    header='true', 
    nullvalue='NA', 
    timestampFormat=\"yyyy-MM-dd'T'HH:mm:ss\", 
    path='/tmp/EvaluacionPitch.csv')
""");

ContextoSql.sql("""
CREATE TABLE IF NOT EXISTS 
ASISTENCIA (
            MarcaTemporal VARCHAR(100), 
            NombreUsuario VARCHAR(100),
            EquipoPertenece VARCHAR(100),
            EquipoExponer VARCHAR(100)
            ) 
USING CSV OPTIONS ( 
    header='true', 
    nullvalue='NA', 
    path='/tmp/AsistenciaPitch.csv')
""");

In [4]:
# 2. Consulte el listado total de estudiantes (correos electrónicos) del 
# curso de Ingeniería de Software, ordenados alfabéticamente
# Tu código a continuación...
#consultas SQL
ContextoSql.sql("SELECT DISTINCT REPLACE(NombreUsuario,' ','') AS NombreUsuario from EVALUACION ORDER BY 1").show()

+--------------------+
|       NombreUsuario|
+--------------------+
| abanolc@unal.edu.co|
|acastrillonv@unal...|
| aflemag@unal.edu.co|
|anapariciom@unal....|
|angutierrezb@unal...|
|anoriega@unal.edu.co|
|auarbelaeza@unal....|
| bocampo@unal.edu.co|
|cgiraldo@unal.edu.co|
|cjfunezg@unal.edu.co|
|cquinchiar@unal.e...|
| dadazam@unal.edu.co|
|daestradam@unal.e...|
|davgarciava@unal....|
|dballesteroso@una...|
|  dbrito@unal.edu.co|
|dcadavid@unal.edu.co|
|dcardonaal@unal.e...|
|dchavarriar@unal....|
|dgarciabl@unal.ed...|
+--------------------+
only showing top 20 rows

In [5]:
# 3. Consulte la cantidad de asistencias registradas por estudiante; además, la fecha y hora de la primera asistencia
# y la fecha y hora de la última asistencia
# Tu código a continuación...
ContextoSql.sql("""SELECT REPLACE(NombreUsuario,' ','') AS NombreUsuario
                , COUNT(*) AS CantidadAsistencias
                , MIN(MarcaTemporal) AS FechaHoraPrimeraAsistencia
                , MAX(MarcaTemporal) AS FechaHoraUltimaAsistencia
            FROM ASISTENCIA 
            GROUP BY NombreUsuario
            ORDER BY 1 """).show()

+--------------------+-------------------+--------------------------+-------------------------+
|       NombreUsuario|CantidadAsistencias|FechaHoraPrimeraAsistencia|FechaHoraUltimaAsistencia|
+--------------------+-------------------+--------------------------+-------------------------+
| abanolc@unal.edu.co|                  7|      2021/04/08 8:12:1...|     2021/04/13 9:37:5...|
|acastrillonv@unal...|                  8|      2021/04/08 8:13:0...|     2021/04/13 9:43:1...|
| aflemag@unal.edu.co|                  8|      2021/04/08 8:11:5...|     2021/04/13 9:41:5...|
|anapariciom@unal....|                 10|      2021/04/08 8:11:4...|     2021/04/13 9:38:5...|
|angutierrezb@unal...|                  8|      2021/04/08 8:19:0...|     2021/04/13 9:43:5...|
|anoriega@unal.edu.co|                  8|      2021/04/08 8:15:1...|     2021/04/13 9:40:2...|
|auarbelaeza@unal....|                  8|      2021/04/08 8:09:5...|     2021/04/13 9:41:0...|
| bocampo@unal.edu.co|                  8|      2021/04/08 8:13:3...|     2021/04/13 9:42:1...|
|cgiraldo@unal.edu.co|                  8|      2021/04/08 8:44:2...|     2021/04/13 9:56:4...|
|cjfunezg@unal.edu.co|                  8|      2021/04/08 8:12:1...|     2021/04/13 9:41:4...|
|cquinchiar@unal.e...|                  6|      2021/04/08 8:33:3...|     2021/04/13 9:49:0...|
| dadazam@unal.edu.co|                  9|      2021/04/08 8:13:1...|     2021/04/13 9:41:1...|
|daestradam@unal.e...|                  8|      2021/04/08 8:10:3...|     2021/04/13 9:44:3...|
|davgarciava@unal....|                  8|      2021/04/08 8:13:4...|     2021/04/13 9:42:3...|
|dballesteroso@una...|                  8|      2021/04/08 8:14:2...|     2021/04/13 9:49:0...|
|  dbrito@unal.edu.co|                  7|      2021/04/08 8:19:0...|     2021/04/13 9:41:3...|
|dcadavid@unal.edu.co|                  8|      2021/04/08 8:13:0...|     2021/04/13 9:40:5...|
|dcardonaal@unal.e...|                  8|      2021/04/08 8:12:0...|     2021/04/13 9:42:1...|
|dchavarriar@unal....|                  8|      2021/04/08 8:13:0...|     2021/04/13 9:43:5...|
|dgarciabl@unal.ed...|                  9|      2021/04/08 10:00:...|     2021/04/13 9:41:0...|
+--------------------+-------------------+--------------------------+-------------------------+
only showing top 20 rows

In [6]:
# 4. Consulte el listado de estudiantes que asistieron a 2 presentaciones o menos (una).
# Tu código a continuación...
ContextoSql.sql("SELECT NombreUsuario from ASISTENCIA GROUP BY NombreUsuario HAVING COUNT(NombreUsuario)<=2").show()

+--------------------+
|       NombreUsuario|
+--------------------+
|jdroldano@unal.ed...|
+--------------------+

In [7]:
# 5. Consulte el listado de estudiantes que no asistieron a ninguna presentación.
# Tu código a continuación...
ContextoSql.sql("""SELECT DISTINCT evaluacion.NombreUsuario 
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                WHERE asistencia.NombreUsuario IS NULL""").show()

+-------------+
|NombreUsuario|
+-------------+
+-------------+

In [8]:
# 6. Consulte los integrantes por cada equipo al que pertenecen.
# Tu código a continuación...
ContextoSql.sql("""SELECT DISTINCT NombreUsuario,REPLACE(EquipoPertenece,'Pertenezco a: ','') AS EquipoPertenece
                FROM ASISTENCIA
                ORDER BY EquipoPertenece,NombreUsuario""").show()

+--------------------+--------------------+
|       NombreUsuario|     EquipoPertenece|
+--------------------+--------------------+
|angutierrezb@unal...|Administración de...|
| eapenad@unal.edu.co|Administración de...|
|emflorezb@unal.ed...|Administración de...|
|framirezf@unal.ed...|Administración de...|
|jhcordoba@unal.ed...|Administración de...|
| jortize@unal.edu.co|Administración de...|
| kmolano@unal.edu.co|Administración de...|
|lumarinb@unal.edu.co|Administración de...|
|nsalinas@unal.edu.co|Administración de...|
|rmbuilesm@unal.ed...|Administración de...|
|saespinosab@unal....|Administración de...|
|samolinap@unal.ed...|Administración de...|
|sednarvaezna@unal...|Administración de...|
| abanolc@unal.edu.co|Gestión de Menús ...|
|anapariciom@unal....|Gestión de Menús ...|
|davgarciava@unal....|Gestión de Menús ...|
|emlopezr@unal.edu.co|Gestión de Menús ...|
|favasquezj@unal.e...|Gestión de Menús ...|
|hriveraa@unal.edu.co|Gestión de Menús ...|
|jcardonaso@unal.e...|Gestión de Menús ...|
+--------------------+--------------------+
only showing top 20 rows

In [9]:
# 7. Consulte la cantidad de asistentes por presentación, sin considerar los asistentes que pertenecen 
# al equipo que realizó la presentación.
# Tu código a continuación...
ContextoSql.sql("""SELECT REPLACE(asistencia.EquipoExponer,'Expone: ','') AS EquipoExponer,COUNT(asistencia.NombreUsuario) AS CantidadAsistentes
                FROM ASISTENCIA asistencia
                WHERE REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','') != REPLACE(asistencia.EquipoExponer,'Expone: ','') 
                GROUP BY asistencia.EquipoExponer
                ORDER BY asistencia.EquipoExponer""").show()

+--------------------+------------------+
|       EquipoExponer|CantidadAsistentes|
+--------------------+------------------+
|Administración de...|                70|
|Deserción de estu...|                 3|
|Gestión de Menús ...|                72|
|Gestión de Reside...|                72|
|Gestión de progra...|                74|
|Lo tengo y te lo ...|                75|
|     Mi Sanandresito|                72|
|Servicios a domic...|                76|
|       Te lo cambio.|                75|
+--------------------+------------------+

In [10]:
# 8. Consutar cuáles integrantes evaluaron a su propio equipo. Estas evaluaciones no serán válidas, pues un
# integrante no puede evaluar a su propio equipo.
# Tu código a continuación...
ContextoSql.sql("""SELECT DISTINCT evaluacion.NombreUsuario, evaluacion.EquipoEvaluar
                FROM EVALUACION evaluacion
                INNER JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','') = evaluacion.EquipoEvaluar""").show()

+--------------------+--------------------+
|       NombreUsuario|       EquipoEvaluar|
+--------------------+--------------------+
| kmolano@unal.edu.co|Administración de...|
|anapariciom@unal....|Servicios a domic...|
|hriveraa@unal.edu.co|Gestión de Menús ...|
|mcarvajalsa@unal....|Gestión de Reside...|
|  lmayar@unal.edu.co|Gestión de progra...|
| jruedat@unal.edu.co|Servicios a domic...|
|daestradam@unal.e...|Lo tengo y te lo ...|
|jhcordoba@unal.ed...|Administración de...|
+--------------------+--------------------+

In [11]:
# 9. Consultar la nota promedio por cada ítem (1 al 15), y la nota promedio total del cada equipo. Recuerde que no
# son válidas las evaluaciones realizadas por los miembros del mismo equipo.
# Tu código a continuación...

# Promedio por pregunta
ContextoSql.sql("""SELECT 
                    ROUND(AVG(Pregunta1),1) AS P1,
                    ROUND(AVG(Pregunta2),1) AS P2,
                    ROUND(AVG(Pregunta3),1) AS P3,
                    ROUND(AVG(Pregunta4),1) AS P4,
                    ROUND(AVG(Pregunta5),1) AS P5,
                    ROUND(AVG(Pregunta6),1) AS P6,
                    ROUND(AVG(Pregunta7),1) AS P7,
                    ROUND(AVG(Pregunta8),1) AS P8,
                    ROUND(AVG(Pregunta9),1) AS P9,
                    ROUND(AVG(Pregunta10),1) AS P10,
                    ROUND(AVG(Pregunta11),1) AS P11,
                    ROUND(AVG(Pregunta12),1) AS P12,
                    ROUND(AVG(Pregunta13),1) AS P13,
                    ROUND(AVG(Pregunta14),1) AS P14,
                    ROUND(AVG(Pregunta15),1) AS P15
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL""").show();

# Promedio por pregunta por equipo y promedio total de equipo
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar,
                    ROUND(AVG(Pregunta1),2) AS Pregunta1,
                    ROUND(AVG(Pregunta2),2) AS Pregunta2,
                    ROUND(AVG(Pregunta3),2) AS Pregunta3,
                    ROUND(AVG(Pregunta4),2) AS Pregunta4,
                    ROUND(AVG(Pregunta5),2) AS Pregunta5,
                    ROUND(AVG(Pregunta6),2) AS Pregunta6,
                    ROUND(AVG(Pregunta7),2) AS Pregunta7,
                    ROUND(AVG(Pregunta8),2) AS Pregunta8,
                    ROUND(AVG(Pregunta9),2) AS Pregunta9,
                    ROUND(AVG(Pregunta10),2) AS Pregunta10,
                    ROUND(AVG(Pregunta11),2) AS Pregunta11,
                    ROUND(AVG(Pregunta12),2) AS Pregunta12,
                    ROUND(AVG(Pregunta13),2) AS Pregunta13,
                    ROUND(AVG(Pregunta14),2) AS Pregunta14,
                    ROUND(AVG(Pregunta15),2) AS Pregunta15,
                    ROUND(AVG((Pregunta1+Pregunta2+Pregunta3+Pregunta4+Pregunta5+Pregunta6+Pregunta7+Pregunta8+Pregunta9+Pregunta10+Pregunta11+Pregunta12+Pregunta13+Pregunta14+Pregunta15)/15),2) AS NotaPomedioTotal
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY evaluacion.EquipoEvaluar""").show()

+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
| P1| P2| P3| P4| P5| P6| P7| P8| P9|P10|P11|P12|P13|P14|P15|
+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|4.4|4.3|4.4|4.2|4.4|4.4|4.2|4.3|4.2|4.4|4.2|4.5|4.4|4.4|4.5|
+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+

+--------------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------------+
|       EquipoEvaluar|Pregunta1|Pregunta2|Pregunta3|Pregunta4|Pregunta5|Pregunta6|Pregunta7|Pregunta8|Pregunta9|Pregunta10|Pregunta11|Pregunta12|Pregunta13|Pregunta14|Pregunta15|NotaPomedioTotal|
+--------------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------------+
|Administración de...|      4.1|     4.38|     3.96|     3.91|     4.18|     4.43|     4.03|      4.4|     3.94|       4.4|      4.12|      4.13|      4.31|      4.19|      4.12|            4.17|
|Deserción de estu...|      4.5|      5.0|      5.0|      5.0|      4.5|      5.0|      5.0|      4.5|      5.0|       4.5|       4.5|       5.0|       4.5|       4.5|       5.0|            4.77|
|Gestión de Menús ...|     4.32|     3.97|     4.57|     4.33|     4.38|     4.03|     4.19|     4.24|     4.29|      4.64|      4.31|       4.5|      4.44|      4.46|      4.74|            4.36|
|Gestión de Reside...|     4.54|     4.43|     4.65|     4.47|     4.46|     4.12|     4.51|     4.68|      4.4|      4.53|      4.34|      4.65|      4.41|      4.54|      4.41|            4.48|
|Gestión de progra...|     4.39|     4.39|     4.53|      3.9|     4.32|     4.44|     4.39|     4.49|     4.25|      4.31|      4.51|      4.42|      4.46|      4.47|      4.61|            4.39|
|Lo tengo y te lo ...|     4.49|      4.6|     4.27|     4.43|     4.43|     4.71|     4.36|     4.26|     4.49|      4.47|      4.36|      4.59|      4.53|       4.6|      4.61|            4.48|
|     Mi Sanandresito|     4.19|      3.9|     4.29|      4.0|     4.32|      4.3|     4.23|     4.38|     3.52|      4.36|      4.37|      4.63|      4.26|      4.16|      4.12|             4.2|
|Servicios a domic...|     4.53|     4.66|     4.53|     4.29|     4.51|      4.6|     4.11|     4.14|     4.36|      4.29|      4.17|      4.66|      4.49|      4.59|      4.61|            4.44|
|       Te lo cambio.|     4.35|     4.04|     4.21|     4.01|     4.45|     4.82|     4.08|     4.08|     4.21|      4.32|      3.62|      4.49|      4.58|      4.46|      4.54|            4.29|
+--------------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------------+

In [28]:
# 10. Consulte el mejor equipo evaluado por cada ítem (según nota promedio. En caso de empate mostrar todos los empatados) 
# y el mejor equipo según el promedio total.
# Tu código a continuación...

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta1),2) as Pregunta1
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta1) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta2),2) as Pregunta2
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta2) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta3),2) as Pregunta3
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta3) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta4),2) as Pregunta4
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta4) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta5),2) as Pregunta5
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta5) desc
                LIMIT 2""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta6),2) as Pregunta6
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta6) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta7),2) as Pregunta7
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta7) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta8),2) as Pregunta8
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta8) desc
                LIMIT 1""").show()
				
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta9),2) as Pregunta9
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta9) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta10),2) as Pregunta10
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta10) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta11),2) as Pregunta11
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta11) desc
                LIMIT 2""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta12),2) as Pregunta12
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta12) desc
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta13),2) as Pregunta13
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta13) desc
                LIMIT 1""").show()		

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta14),2) as Pregunta14
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta14) desc
                LIMIT 2""").show() 
    
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta15),2) as Pregunta15
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta15) desc
                LIMIT 1""").show()
    
    
# Mejor equipo por promedio total

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar,
                    ROUND(AVG((Pregunta1+Pregunta2+Pregunta3+Pregunta4+Pregunta5+Pregunta6+Pregunta7+Pregunta8+Pregunta9+Pregunta10+Pregunta11+Pregunta12+Pregunta13+Pregunta14+Pregunta15)/15),1) AS NotaPomedioTotal
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY ROUND(AVG((Pregunta1+Pregunta2+Pregunta3+Pregunta4+Pregunta5+Pregunta6+Pregunta7+Pregunta8+Pregunta9+Pregunta10+Pregunta11+Pregunta12+Pregunta13+Pregunta14+Pregunta15)/15),1) DESC
                LIMIT 3""").show()

+--------------------+---------+
|       EquipoEvaluar|Pregunta1|
+--------------------+---------+
|Gestión de Reside...|     4.54|
|Servicios a domic...|     4.53|
|Deserción de estu...|      4.5|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta2|
+--------------------+---------+
|Deserción de estu...|      5.0|
|Servicios a domic...|     4.66|
|Lo tengo y te lo ...|      4.6|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta3|
+--------------------+---------+
|Deserción de estu...|      5.0|
|Gestión de Reside...|     4.65|
|Gestión de Menús ...|     4.57|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta4|
+--------------------+---------+
|Deserción de estu...|      5.0|
|Gestión de Reside...|     4.47|
|Lo tengo y te lo ...|     4.43|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta5|
+--------------------+---------+
|Servicios a domic...|     4.51|
|Deserción de estu...|      4.5|
|Gestión de Reside...|     4.46|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta6|
+--------------------+---------+
|Deserción de estu...|      5.0|
|       Te lo cambio.|     4.82|
|Lo tengo y te lo ...|     4.71|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta7|
+--------------------+---------+
|Deserción de estu...|      5.0|
|Gestión de Reside...|     4.51|
|Gestión de progra...|     4.39|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta8|
+--------------------+---------+
|Gestión de Reside...|     4.68|
|Deserción de estu...|      4.5|
|Gestión de progra...|     4.49|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta9|
+--------------------+---------+
|Deserción de estu...|      5.0|
|Lo tengo y te lo ...|     4.49|
|Gestión de Reside...|      4.4|
+--------------------+---------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta10|
+--------------------+----------+
|Gestión de Menús ...|      4.64|
|Gestión de Reside...|      4.53|
|Deserción de estu...|       4.5|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta11|
+--------------------+----------+
|Gestión de progra...|      4.51|
|Deserción de estu...|       4.5|
|     Mi Sanandresito|      4.37|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta12|
+--------------------+----------+
|Deserción de estu...|       5.0|
|Servicios a domic...|      4.66|
|Gestión de Reside...|      4.65|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta13|
+--------------------+----------+
|       Te lo cambio.|      4.58|
|Lo tengo y te lo ...|      4.53|
|Deserción de estu...|       4.5|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta14|
+--------------------+----------+
|Lo tengo y te lo ...|       4.6|
|Servicios a domic...|      4.59|
|Gestión de Reside...|      4.54|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta15|
+--------------------+----------+
|Deserción de estu...|       5.0|
+--------------------+----------+

+--------------------+----------------+
|       EquipoEvaluar|NotaPomedioTotal|
+--------------------+----------------+
|Deserción de estu...|             4.8|
|Lo tengo y te lo ...|             4.5|
|Gestión de Reside...|             4.5|
+--------------------+----------------+

In [29]:
# 11. Consulte el peor equipo evaluado por cada ítem (según nota promedio. En caso de empate mostrar todos los empatados) 
# y el peor equipo según el promedio total.
# Tu código a continuación...

#Peor Equipo por Pregunta
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta1),2) as Pregunta1
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta1) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta2),2) as Pregunta2
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta2) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta3),2) as Pregunta3
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta3) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta4),2) as Pregunta4
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta4) 
                LIMIT 2""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta5),2) as Pregunta5
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta5) 
                LIMIT 3""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta6),2) as Pregunta6
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta6) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta7),2) as Pregunta7
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta7) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta8),2) as Pregunta8
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta8) 
                LIMIT 1""").show()
				
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta9),2) as Pregunta9
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta9) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta10),2) as Pregunta10
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta10) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta11),2) as Pregunta11
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta11) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta12),2) as Pregunta12
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta12) 
                LIMIT 1""").show()

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta13),2) as Pregunta13
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta13) 
                LIMIT 1""").show()		

ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta14),2) as Pregunta14
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta14) 
                LIMIT 1""").show() 
    
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar, ROUND(AVG(evaluacion.Pregunta15),2) as Pregunta15
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY AVG(evaluacion.Pregunta15) 
                LIMIT 1""").show()

# Peor equipo por promedio total
ContextoSql.sql("""SELECT evaluacion.EquipoEvaluar,
                    ROUND(AVG((Pregunta1+Pregunta2+Pregunta3+Pregunta4+Pregunta5+Pregunta6+Pregunta7+Pregunta8+Pregunta9+Pregunta10+Pregunta11+Pregunta12+Pregunta13+Pregunta14+Pregunta15)/15),1) AS NotaPomedioTotal
                FROM EVALUACION evaluacion
                LEFT JOIN ASISTENCIA asistencia 
                    ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                    AND evaluacion.EquipoEvaluar = REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','')
                WHERE asistencia.NombreUsuario IS NULL
                    AND asistencia.EquipoPertenece IS NULL
                GROUP BY evaluacion.EquipoEvaluar
                ORDER BY ROUND(AVG((Pregunta1+Pregunta2+Pregunta3+Pregunta4+Pregunta5+Pregunta6+Pregunta7+Pregunta8+Pregunta9+Pregunta10+Pregunta11+Pregunta12+Pregunta13+Pregunta14+Pregunta15)/15),1) ASC
                LIMIT 3""").show()

+--------------------+---------+
|       EquipoEvaluar|Pregunta1|
+--------------------+---------+
|Administración de...|      4.1|
|     Mi Sanandresito|     4.19|
|Gestión de Menús ...|     4.32|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta2|
+--------------------+---------+
|     Mi Sanandresito|      3.9|
|Gestión de Menús ...|     3.97|
|       Te lo cambio.|     4.04|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta3|
+--------------------+---------+
|Administración de...|     3.96|
|       Te lo cambio.|     4.21|
|Lo tengo y te lo ...|     4.27|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta4|
+--------------------+---------+
|Gestión de progra...|      3.9|
|Administración de...|     3.91|
|     Mi Sanandresito|      4.0|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta5|
+--------------------+---------+
|Administración de...|     4.18|
|     Mi Sanandresito|     4.32|
|Gestión de progra...|     4.32|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta6|
+--------------------+---------+
|Gestión de Menús ...|     4.03|
|Gestión de Reside...|     4.12|
|     Mi Sanandresito|      4.3|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta7|
+--------------------+---------+
|Administración de...|     4.03|
|       Te lo cambio.|     4.08|
|Servicios a domic...|     4.11|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta8|
+--------------------+---------+
|       Te lo cambio.|     4.08|
|Servicios a domic...|     4.14|
|Gestión de Menús ...|     4.24|
+--------------------+---------+

+--------------------+---------+
|       EquipoEvaluar|Pregunta9|
+--------------------+---------+
|     Mi Sanandresito|     3.52|
|Administración de...|     3.94|
|       Te lo cambio.|     4.21|
+--------------------+---------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta10|
+--------------------+----------+
|Servicios a domic...|      4.29|
|Gestión de progra...|      4.31|
|       Te lo cambio.|      4.32|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta11|
+--------------------+----------+
|       Te lo cambio.|      3.62|
|Administración de...|      4.12|
|Servicios a domic...|      4.17|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta12|
+--------------------+----------+
|Administración de...|      4.13|
|Gestión de progra...|      4.42|
|       Te lo cambio.|      4.49|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta13|
+--------------------+----------+
|     Mi Sanandresito|      4.26|
|Administración de...|      4.31|
|Gestión de Reside...|      4.41|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta14|
+--------------------+----------+
|     Mi Sanandresito|      4.16|
|Administración de...|      4.19|
|Gestión de Menús ...|      4.46|
+--------------------+----------+

+--------------------+----------+
|       EquipoEvaluar|Pregunta15|
+--------------------+----------+
|Administración de...|      4.12|
+--------------------+----------+

+--------------------+----------------+
|       EquipoEvaluar|NotaPomedioTotal|
+--------------------+----------------+
|Administración de...|             4.2|
|     Mi Sanandresito|             4.2|
|       Te lo cambio.|             4.3|
+--------------------+----------------+

In [14]:
# 12. Consulte la lista de estudiantes con la correspondiente nota obtenida en la presentación 
# (nota promedio total de la evaluación obtenida por el equipo)
# Tu código a continuación...
ContextoSql.sql("""SELECT Nota.NombreUsuario, Nota.EquipoPertenece, evaluacion.NotaPomedioTotal
                FROM 
                (
                    SELECT evaluacion.EquipoEvaluar,
                        ROUND(AVG((Pregunta1+Pregunta2+Pregunta3+Pregunta4+Pregunta5+Pregunta6+Pregunta7+Pregunta8+Pregunta9+Pregunta10+Pregunta11+Pregunta12+Pregunta13+Pregunta14+Pregunta15)/15),2) AS NotaPomedioTotal
                    FROM EVALUACION evaluacion
                    LEFT JOIN ASISTENCIA asistencia 
                        ON evaluacion.NombreUsuario = asistencia.NombreUsuario
                        AND REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','') = evaluacion.EquipoEvaluar
                     WHERE asistencia.NombreUsuario IS NULL
                         AND asistencia.EquipoPertenece IS NULL
                     GROUP BY evaluacion.EquipoEvaluar           
                ) evaluacion
                INNER JOIN (
                    SELECT DISTINCT REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','') AS EquipoPertenece,asistencia.NombreUsuario
                    FROM ASISTENCIA asistencia
                    WHERE REPLACE(asistencia.EquipoPertenece,'Pertenezco a: ','') != REPLACE(asistencia.EquipoExponer,'Expone: ','') 
                ) Nota ON Evaluacion.EquipoEvaluar = Nota.EquipoPertenece
                ORDER BY 2,1""").show()

+--------------------+--------------------+----------------+
|       NombreUsuario|     EquipoPertenece|NotaPomedioTotal|
+--------------------+--------------------+----------------+
|angutierrezb@unal...|Administración de...|            4.17|
| eapenad@unal.edu.co|Administración de...|            4.17|
|emflorezb@unal.ed...|Administración de...|            4.17|
|framirezf@unal.ed...|Administración de...|            4.17|
|jhcordoba@unal.ed...|Administración de...|            4.17|
| jortize@unal.edu.co|Administración de...|            4.17|
| kmolano@unal.edu.co|Administración de...|            4.17|
|lumarinb@unal.edu.co|Administración de...|            4.17|
|nsalinas@unal.edu.co|Administración de...|            4.17|
|rmbuilesm@unal.ed...|Administración de...|            4.17|
|saespinosab@unal....|Administración de...|            4.17|
|samolinap@unal.ed...|Administración de...|            4.17|
|sednarvaezna@unal...|Administración de...|            4.17|
| abanolc@unal.edu.co|Gestión de Menús ...|            4.36|
|anapariciom@unal....|Gestión de Menús ...|            4.36|
|davgarciava@unal....|Gestión de Menús ...|            4.36|
|emlopezr@unal.edu.co|Gestión de Menús ...|            4.36|
|favasquezj@unal.e...|Gestión de Menús ...|            4.36|
|hriveraa@unal.edu.co|Gestión de Menús ...|            4.36|
|jcardonaso@unal.e...|Gestión de Menús ...|            4.36|
+--------------------+--------------------+----------------+
only showing top 20 rows